### PR TITLE
FRDQ-47

### PR DESCRIPTION
**Pull request by Krysik**

### CODE REVIEW

**Comment by Krysik** [comment]
I don't know how to trigger this action. Does it trigger on PR into the main branch?

**Comment by hayuna** [comment]
#47

**Comment by hayuna** [comment]
> I don't know how to trigger this action. Does it trigger on PR into the main branch?

This action start executing when any changes will be applied to pull request

**Comment by Krysik** [comment]
Please, after review squash and merge ;p

**Pull request merged**
